// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Goal struct {
	ID          string  `json:"id"`
	User        *User   `json:"user"`
	Name        string  `json:"name"`
	Amount      float64 `json:"amount"`
	Description *string `json:"description,omitempty"`
	Link        *string `json:"link,omitempty"`
	Image       *string `json:"image,omitempty"`
	AddedAt     string  `json:"added_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type Mutation struct {
}

type NewGoal struct {
	Name        string  `json:"name"`
	Amount      float64 `json:"amount"`
	Description *string `json:"description,omitempty"`
	Link        *string `json:"link,omitempty"`
	Image       *string `json:"image,omitempty"`
}

type NewUser struct {
	LastName     *string `json:"last_name,omitempty"`
	FirstName    *string `json:"first_name,omitempty"`
	UserName     string  `json:"user_name"`
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
}

type Query struct {
}

type UpdateUser struct {
	LastName     *string `json:"last_name,omitempty"`
	FirstName    *string `json:"first_name,omitempty"`
	UserName     *string `json:"user_name,omitempty"`
	Email        *string `json:"email,omitempty"`
	PasswordHash *string `json:"password_hash,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	LastName  *string `json:"last_name,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	UserName  string  `json:"user_name"`
	Email     string  `json:"email"`
	AddedAt   string  `json:"added_at"`
	UpdatedAt string  `json:"updated_at"`
}
