gen_all_rpc: gen_saving gen_config gen_database gen_user gen_valorant

gen_saving:
	cd rpc/saving && buf generate	

gen_config:
	cd rpc/config && buf generate	

gen_database:
	cd rpc/database && buf generate	

gen_user:
	cd rpc/user && buf generate	

gen_valorant:
	cd rpc/valorant && buf generate	
