package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"context"
	"fmt"

	"mariusihring.dev/graphql/graph/model"
)

// CreateGoal is the resolver for the createGoal field.
func (r *mutationResolver) CreateGoal(ctx context.Context, input model.NewGoal) (*model.Goal, error) {
	panic(fmt.Errorf("not implemented: CreateGoal - createGoal"))
}

// GetGoal is the resolver for the getGoal field.
func (r *queryResolver) GetGoal(ctx context.Context, id string) (*model.Goal, error) {
	panic(fmt.Errorf("not implemented: GetGoal - getGoal"))
}
