// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: valorant.proto

package valorantservice

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// ValorantServiceClient is the client API for ValorantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValorantServiceClient interface {
}

type valorantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValorantServiceClient(cc grpc.ClientConnInterface) ValorantServiceClient {
	return &valorantServiceClient{cc}
}

// ValorantServiceServer is the server API for ValorantService service.
// All implementations must embed UnimplementedValorantServiceServer
// for forward compatibility
type ValorantServiceServer interface {
	mustEmbedUnimplementedValorantServiceServer()
}

// UnimplementedValorantServiceServer must be embedded to have forward compatible implementations.
type UnimplementedValorantServiceServer struct {
}

func (UnimplementedValorantServiceServer) mustEmbedUnimplementedValorantServiceServer() {}

// UnsafeValorantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValorantServiceServer will
// result in compilation errors.
type UnsafeValorantServiceServer interface {
	mustEmbedUnimplementedValorantServiceServer()
}

func RegisterValorantServiceServer(s grpc.ServiceRegistrar, srv ValorantServiceServer) {
	s.RegisterService(&ValorantService_ServiceDesc, srv)
}

// ValorantService_ServiceDesc is the grpc.ServiceDesc for ValorantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValorantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.valorantservice.ValorantService",
	HandlerType: (*ValorantServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "valorant.proto",
}
